base_path: /websensepub/
permalink: /websensepub/blog/:title.html
pygments: true

prose:
  siteurl: 'http://madaboutcode.com/websensepub/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Choose Author"
          options:
            - name: "Vimal"
              value: "Vimal"
            - name: "Praveen"
              value: "Praveen"
            - name: "Ajeesh"
              value: "Ajeesh"
      - name: "summary"
        field:
          element: "textarea"
          label: "Preview Text"
          help: "Preview text visible in the article listing page"
      - name: "splash"
        field:
          element: "text"
          label: "Splash image for the post"
          type: text
          placeholder: "media/something.jpg"
      - name: "forreview"
        field:
          element: "checkbox"
          label: "Draft, don't show on site"
          value: false

