base_path: /websensepub/
permalink: /websensepub/blog/:title.html
#base_path: /
#permalink: /blog/:title.html
pygments: true

prose:
  siteurl: 'http://madaboutcode.com/websensepub/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title of the post"
          placeholder: "<post title>"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Choose Author"
          options:
            - name: "Vimal"
              value: "Vimal"
            - name: "Praveen"
              value: "Praveen"
            - name: "Ajeesh"
              value: "Ajeesh"
      - name: "summary"
        field:
          element: "textarea"
          label: "Preview Text"
      - name: "splash"
        field:
          element: "text"
          label: "Splash image for the post"
          type: text
          placeholder: "media/something.jpg"
