base_path: /websensepub/
permalink: /websensepub/blog/:title.html
pygments: true

prose:
  rooturl: '_posts'
  siteurl: 'http://madaboutcode.com/websensepub/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
